

services:
  db:
    image: postgres:17
    container_name: my_postgres_stokvel
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stokvel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"   # backend exposed on localhost:5000
    volumes:
      - ./backend:/app   # hot-reload for dev
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://admin:secret@db:5432/mydb  # connection string
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"   # frontend exposed on localhost:3000
    volumes:
      - ./frontend:/app   # hot-reload for dev
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend 

volumes:
  postgres_data:
